### ISSUE TITLE
Cannot open link Awesome-Batch-Reinforcement-Learning

### ISSUE THREAD

**Issue by cameron-chen** [kristery/Awesome-Imitation-Learning#4]
Cannot open two links to Awesome-{Model-Based-Reinforcement-Learning, Batch-Reinforcement-Learning}. Can you please check?

**Comment by kristery** [comment]
I have removed the two repos since I no longer maintain them. Sorry for the inconvenience.

**Comment by cameron-chen** [comment]
Noted, thank you!
